### ISSUE TITLE
bug: list with two elements are parsed as `Input`

### ISSUE THREAD

**Issue by wangl-cc** [MaaAssistantArknights/maa-cli#68]
The a value like below:

```toml
[tasks.params]
shopping = true
credit_fight = true
buy_first = ["招聘许可", "龙门币"]
blacklist = ["碳", "家具", "加急许可"]
```

The `buy_first` are parsed as a `Input`:
<img width="307" alt="Screenshot 2023-10-08 at 20 37 44" src="https://github.com/MaaAssistantArknights/maa-cli/assets/40141251/725bb8c0-fcd8-4b0a-931c-57d234d4ea3a">
